using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Translate  {

	public  static Dictionary<string,string> Dictionary =
           new Dictionary<string, string>()
        {
            //a
            {"问候", "ai"}, {"嘴巴", "angalj"},
            {"喜帖", "akagami"}, {"完成", "anga-"},
            {"八", "alu"}, {"还是", "anan"},
            {"孩子", "aljak"}, {"剩下", "amin"},
            {"因为", "ayatua"}, {"朋友", "adju"},
            {"槟榔", "apu"}, {"不知道", "adjav"},
            {"芋头干", "aradj"}, {"ㄧ起走吧", "ariqa"},
            {"油桐花", "abulagi"}, {"除草", "asik"},
            {"为...留下", "adjuqan"}, {"危险", "abunai"},
            {"忘了", "alim"}, {"记不得", "alim"},
            {"火柴", "anasui"},{"渔网", "arai"},
            {"请为...留一些了", "adjuqianga"},{"蜘蛛", "akumakuma"},
            {"什么", "anema"},{"八元", "aluavatan"},
            {"那", "azua"},{"怀念", "aianga"},
            {"被…拿", "alapen"},{"排香草", "atap"},
            {"月经", "adjaq"},{"是", "avan"},
            {"牙齿", "aljis"},{"糖", "alju"},
            {"蜂蜜", "alju"},{"这样说", "aya"},
            {"留下", "adjuq-"},{"男子名", "api"},
            {"没有了", "aminanga"},{"捌堆", "aluaqepuan"},
            {"阿美族", "amizuku"},{"也许", "adjav"},
            //b
            {"沙石", "barasu"}, {"水泥平房", "bilanda"},
            {"桶子", "bungbung"}, {"拍打", "benakebak"},
            {"看不起", "beraq-2"}, {"医院", "biuing"},
            {"破洞", "buang"}, {"最差的", "biribirian"},
            {"电池", "batili"}, {"吹嘘", "beriq"},
            {"屁声", "beriq"},{"放屁", "beriq"},
            {"球", "buru"}, {"打洞", "benerung"},
            {"有弹性", "balukbuk"}, {"杀虫剂", "bangacui"},
            {"包办", "benau"}, {"欺骗", "beneraq"},
            {"正在打球", "benuruburu"}, {"鼻塞", "benges"},
            {"欺骗", "beraq-"}, {"泡泡", "bubung"},
            {"泡沫", "bubung"}, {"吹泡泡", "benubung"},
            {"份", "bau"}, {"喷出", "beres-"},
            {"牧师", "buksi"}, {"吹牛", "beririq"},
            {"用水泥建造的", "binilanda"}, {"被骗", "binulung"},
            {"龙虾", "bangu"}, {"鸭", "bibi"},
            {"树上的蚂蚁窝", "buljek"}, {"秃秃的", "banabanal"},
            {"拍打声", "baqbaq"}, {"轰隆隆声", "barengbeng"},
            {"喷", "beneres"}, {"电动理发器", "balikan"},
            {"最后", "biri"},{"殿后", "biri"},
            {"浸水", "buqbuq-"}, {"沉下水里", "buqbuq-"},
            {"打球", "benuru"}, {"啤酒", "biru"},
            {"葡萄", "budu"}, {"佛教", "bukiu"},
            {"拔掉", "beljutjen"}, {"球场", "baburuan"},
            {"公车", "basu"}, {"独角仙", "bereng"},
            {"布农族", "bunung"}, {"骗人", "benulung"},
            {"米粉", "bihun"}, {"便当", "bintu"},
            {"灰尘", "buljang"},{"骗", "bulung"}, 
            {"骗人", "bulung"},{"沙石做的", "binarasu"},
            {"把…沉下水里", "benuqbuq"}, {"庙宇", "biu"},
            {"喷气", "bus-"}, {"昵称小男孩", "buya"},
            {"风呼呼声", "barusbus"}, {"胭脂", "bahun"},
            {"病菌", "baiking"}, {"拉断", "beljutj-"},
            {"脱落", "beljutj-"},{"拔掉", "beljutj-"},
            {"泥泞", "beneq"},{"被拉断", "bineljutj"},
            {"喷洒器", "busbus"}, {"喷洒", "benusbus"},
            {"布农族", "bununzuku"}, {"洞", "berung"},
            {"驱赶", "bisbis"}, {"蚕蛹", "bukelulj"},
            {"正在喷", "benereberes"}, {"秃头", "banal"},
            {"补搬车", "batabata"}, {"欺骗", "buru2"},
            {"欺骗", "benuru2"},
            //c
            {"疾病；毛病", "saqetjuan"},{"神；灵", "cemas"},
            {"学生", "situ"},{"猎人", "cinunan"},
            {"遇到", "secevung"},{"男子聚会所", "cakar"},
            {"村长", "sunciu"},{"女子名", "cemedas"},
            {"茎；柄", "cuqus"},{"扛下来", "cinavulid"},
            {"干裂；裂开", "cekas"},{"众神；泛灵", "cemacemas"},
            {"重担", "sadjelung-"},{"用刨及削制作木质材料", "cemeqadj"},
            {"士兵", "sivitjai"},{"筹备丧葬费", "sicevelj"},
            {"山羊", "sizi"},{"模仿", "sinikicual"},
            {"梦；运气", "sepi"},{"菜肴", "sinidjamai"},
            {"哀歌", "sicangicangit"},{"背离；迷路", "sekapalak"},
            {"隔热起锅布", "sapelj"},{"太香了", "salumangata"},
            {"社会", "siakai"},{"准备要煮的菜", "semanljaceng"},
            {"舒适；安稳", "suljivatj"},{"晨星", "sikaljialjia"},
            {"轻", "saceqalj"},{"另人毛骨悚然", "sapulju"},
            {"做菜", "semandjamai"},{"种植之物", "siniquma"},
            {"扛", "cemavulid"},{"堆材", "semavac"},
            {"已被清除", "sinuceveljan"},{"表示洁癖", "savaqaran"},
            {"传令", "sinekauljan"},{"猎物", "sacemel"},
            {"向…吐舌", "semema"},{"羡慕、炫耀、指指点点", "saljinga-"},
            {"清洗", "semenav"},{"煮小米用的搅拌匙", "civan "},
            {"四元", "sepatjavatan"},{"标柱；标记；赐封", "cekcek"},
            {"用来绑…", "sivengetj"},{"过往经历", "cinalivatan"},
            {"大蜘蛛", "cacagalj"},{"竹笋；芽；发芽", "cuvuq"},
            {"伸展身体骨头所发出之声响", "caljetuq"},{"苦莴苣菜", "samaq"},
            {"蓝", "cangia"},{"信徒", "sinzia"},
            {"黄杞", "capelju"},{"冰", "sulja"},
            {"报信；邀请；帖子", "ceged"},{"财产", "sauzayan"},
            {"正在读书", "semupusupu"},{"生疏；不来往", "secacadja"},
            {"赶；走；起", "sau"},{"是说…的意思", "siniaya"},
            {"辣椒", "silji"},{"扭干", "semepet"},
            {"杂草丛生", "cemecemel"},{"被...附身", "sezetjen"},
            {"掀开", "cemekalj"},{"羞于…", "siasiaq"},
            {"兼顾", "sicapilj"},{"岁；年度；年份", "cavilj"},
            {"偷偷的(行为)", "sikicakav"},{"午餐", "cengelj"},
            {"立柱", "cemukes"},{"落榜", "caqev"},
            {"摘下", "cempis"},{"盖子", "siniaya"},
            {"辗转听到", "selangeda"},{"编竹筛子", "semantjakaz"},
            {"亲近", "sedjadjeljek"},{"制作腌肉", "emanvaleng"},
            {"采石材", "cemvak 2"},{"蛀虫", "caljameq"},
            {"人力", "cemaucau 1"},{"吹奏法", "sipazaingan"},
            {"解开绳子", "semuqadjai"},{"蛀虫", "caljameq"},
            {"不愿意", "sikaqilji"},{"点火;点燃；起火用具", "cekis"},
            {"停止", "semkez"},{"忙碌", "saliman"},
            {"全部拿光", "seljudjen"},{"断崖", "ceva"},
            {"脱衣服", "semukava"},{"席；垫子", "sekam"},
            {"先、前、第一", "sangas-"},{"并且毁掉", "cepeljuti"},
            {"地理", "cili"},{"盖盖子", "cemaqev"},
            {"助产士", "sanbasang"},{"通报信息", "cemeged"},
            {"内裤", "sarumata"},{"拔下拔取", "cemelu"},
            {"斜眼", "semiqitj"},{"埋藏", "cinevelj"},
            {"考试", "siking"},{"正在煎", "cemiacian"},
            {"刀子", "siqunu"},{"好吃", "sanguaq"},
            {"不喜欢；厌恶", "suqelam"},{"典雅的女孩", "samiling"},
            {"温和；温柔", "sulapelj"},{"跪下", "cemungal"},
            {"喷出", "siberes"},{"取消", "semucikel"},
            {"浸泡于…", "sinibuqbuq"},{"容易饿", "cemulja"},
            {"被倒出来", "sinicaca"},{"斯文", "segalju"},
            {"准备葬礼", "semannamacai"},{"吃一点", "semukeri"},
            {"被虫蛀", "caljameqen"},{"向后仰；人仰马翻", "setjelangalj"},
            {"涌泉源头", "sicevud"},{"委托存放", "sinipapadjeng"},
            {"烤的", "cinapan"},{"极端厉害", "seqazalj"},
            {"堂；表兄弟姊妹", "sikacekelj"},{"做成汤", "sansiaven"},
            {"用来转向之物", "sinipenid"},{"关连；责任；牵涉；顺便；兼顾", "capilj"},
            {"被雨淋", "sepaqudjalj"},{"出书", "semansunatj"},
            {"做饲料", "semanquzu"},{"指引", "situlek"},
            {"敬拜", "sirihayan"},{"牵牛花", "calivuduq"},
            {"先…", "sangasan"},{"闪电", "celalaq"},
            {"天空红红的", "semeliap"},{"蚊子", "sasiq"},
            {"演唱厅", "sasenayan"},{"午时", "cengelj"},
            {"…用来熄火的", "sisevusevus"},{"蚂蚁", "seqsasiqazalj"},
            {"给予", "sivai"},{"安葬", "cemevelj"},
            {"失落感", "suraman"},{"墓地；掩埋场", "caceveljan"},
            {"脱臼", "seveliuq"},{"要包…", "cavuin"},
            {"抛掷", "siveric"},{"折返点", "cacikelan"},
            {"散落", "sevuriad"},{"容易生气", "culiculi"},
            {"使…饥饿", "culjain"},{"回家", "semaumaq"},
            {"跪拜", "cemacungalan"},{"距离；远离", "cadja"},
            {"慢半拍", "sasigalju"},{"被抛弃", "siniveric"},
            {"舒服；舒适", "sangasangasan"},{"唱歌", "semnai"},
            {"第一；首先", "siravarava"},{"有…的味道", "sa-"},
            {"放弃没必要", "sikuda"},{"饭桌", "cukui"},
            {"用来舀", "sikaus"},{"亲戚", "cunguljan"},
            {"色泽鲜美", "sanguanguaq"},{"懒惰", "celaqut"},
            {"充满", "sepeljuq"},{"地球；世界；人间", "cauan"},
            {"令人羡慕", "semaljinga"},{"选为…", "san"},
            {"垫在底部", "sekaman"},{"火", "sapui"},
            {"斜坡的", "calisilisi"},{"痛苦的遭遇；灾难", "siselapai"},
            {"烤箱", "cacapan"},{"吃饭用具", "sikakan"},
            {"挨家挨户传讯", "cemaucau"},{"四月", "sigacu"},
            {"打巴掌", "cemabiljaq"},{"舒适；适宜", "seljenguaq"},
            {"重新获得…", "cempeliv"},{"害羞", "siaqan"},
            {"停", "seceker"},{"读书室(房)", "sasupuan"},
            {"突然生病(遭鬼附身)", "secevung"},{"杂草；草丛；荒野", "cemel"},
            {"适合", "sedjaljep"},{"萝卜", "caitav"},
            {"被撞", "secugcug"},{"铁皮", "ciupan"},
            {"遭埋", "sepacevelj"},{"松开", "suvengetjan"},
            {"贼；小偷", "car"},{"铲平地", "sapai"},
            {"呕气；生气", "culi"},{"阴间", "selem"},
            {"欲…；要…", "saka"},{"你", "sun"},
            {"屋梁", "sialangan"},{"分割；割让", "cemviq"},
            {"香的", "salum"},{"接替；更换", "sevalit"},
            {"男子名", "cunuq"},{"难吃；不好吃；不好喝", "sakuya"},
            {"茄苳树", "cuqu"},{"代替；拿；代收", "sialap"},
            {"确认", "sikeljangan"},{"令人惊讶", "semamalji"},
            {"选为…", "semupusupu"},{"帅哥", "sauqaljai"},
            {"正在数算", "sepacevelj"},{"竹篓", "cepeng"},
            {"忙碌的样子", "sepasepurpurcevelj"},{"刀鞘；刀", "ceqeljap"},
            {"陷阱；绳结", "seluc"},{"领袖；法规", "sasusuan"},
            {"久", "cuai"},{"去年", "sicaviljan"},
            {"工作、制作", "sengseng-"},{"配偶", "cekelj"},
            {"贪;羡慕", "samulja"},{"折磨；极为；加害；更严重", "selapai"},
            {"总统", "cungtung"},{"遇到", "sauqaljai"},
            {"借", "sedjam-"},{"还债", "semukiam"},
            {"村长", "sunciu"},{"真是的", "sarukamayanga"},
            {"被子", "sicauvan"},{"串", "cemusu"},
            {"...过后", "secalivat"},{"门板", "siqeljevan"},
            {"哪里人", "senema"},{"陷阱、吊挂、被勒", "seluc"},
            {"沉睡打鼾", "sarequng"},{"宰杀动物", "cemulju"},
            {"带去", "sivaik"},{"传统美食(专有名词)", "cinavu"},
            {"暂停", "sisekez"},{"打雷闪电", "cemelalaq"},
            {"现在的", "situcuan"},{"生火用", "sipecungu"},
            {"依循", "susu"},{"锁住；锁门", "cemaqcaq"},
            {"闻；嗅", "semequ"},{"祖先", "sevalitan"},
            {"仆人；受仆役的", "sasekauljan"},{"(木制)门楣", "sasuayan"},
            {"配偶、家族、夫妻、成家堂、表兄弟姊妹", "cekelj-"},{"夜晚", "seleman"},
            {"船桨", "civan"},{"偷窃；被偷；隐密", "cakav"},
            {"缝补用的布", "caqis"},{"出现", "sevacaq"},
            {"你", "su"},{"人", "caucau"},
            {"属于", "se"},{"同伴；配偶", "saladj"},
            {"缝补", "caqis"},{"功课", "sasupuin"},
            {"阳光", "cengelaw"},{"某人赠送的…", "sinivai"},
            {"竹杯", "culjui"},{"使人感到腻", "semila"},
            {"生意；买卖；生意人", "siubai"},{"室内储藏室", "salang"},
            {"西装", "sibiru"},{"老师", "sinsi"},
            {"系谱关系", "susu"},{"伤口或皮肤疼痛", "saljengseng"},
            {"避邪", "selem"},{"小米梗", "singilj"},
            {"日出", "cemedas"},{"读书", "supu"},
            {"被打巴掌", "cinabiljaqan"},{"螫", "caljedjen"},
            {"浪费钱", "semupaisu"},{"串成", "cinusu"},
            {"庄重", "samiling"},{"膝盖", "cungal"},
            {"被冲走", "seqaljudj"},{"同情", "saleljeselj"},
            {"职业", "sengsengan"},{"包食物", "cemavu"},
            {"女人味", "savavayan"},{"溺水", "sebuqbuq"},
            {"探索认定", "semusu"},{"缝补了", "cinapel"},
            {"安抚；安慰", "semasa"},{"数算", "supu"},
            {"男子名", "celalaq"},{"畏惧感", "saregem"},
            {"掩埋、安葬、丧葬费", "cevelj"},{"返回；折返", "cemikel"},
            {"仇敌", "cimed"},{"疾病；毛病", "saqetjuan"},
            {"第三代堂；表兄弟姊妹", "sangasangasan"},{"去田里", "semavavua"},
            {"羡慕", "saljinga"},{"进屋内", "sematjumaq"},
            {"寄送", "semusuq"},{"肥皂", "sivatevateq"},
            {"背起", "semevalj"},{"疾病；毛病", "saqetjuan"},
            {"正在选举", "sinkiukiu"},{"肥皂", "saqetjuan"},
            {"户外；外面", "casav"},{"做某事", "sini-"},
            {"准备小米田", "situgutugut"},{"书本", "sunatj"},
            {"槟榔", "saviki"},{"喝多", "semuqaca"},
            {"一起长大之朋友", "seljang"},{"燃烧小米梗产生之熏烟", "semingilj"},
            {"才华", "caquan"},{"耳朵；有耳朵之壶", "calinga"},
            {"驶过", "cemalivat"},{"储存桶", "cadju"},
            {"沾黏", "sedjekec"},{"令人恶心", "semavaqar"},
            {"塌陷", "sikacunuq"},{"然后；而后就", "sa"},
            {"将物品挂于高处", "cemingul"},{"舌头", "sema"},
            {"立柱之处", "cinekecekan"},{"病；痛", "saqetju"},
            {"枕；躺", "sangel"},{"用来盖的", "sicaqev"},
            {"柱子；主柱；柱界", "cukes"},{"威严", "saregem"},
            {"汤", "siav"},{"过不去", "seqelicing"},
            {"情人", "sudju"},{"散播", "seljaljiak"},
            {"去偷", "cemakav"},{"词", "senai"},
            {"过夜", "siuljai"},{"被吵醒", "saugseg"},
            {"包扎伤口", "cemavu"},{"垃圾", "cemel"},
            {"斜坡", "calisi"},{"歇脚之处", "sasekezan"},
            {"箭竹", "cekes"},{"…用来搬运的…", "sisakusakuc"},
            {"四", "sepatj"},{"搬运", "semakuc"},
            {"人名(男子名)", "sulja"},{"用来比喻做", "sinipupatarevan"},
            {"九", "siva"},{"捡骨", "sinuceveljan"},
            {"扣子", "cacaingan"},{"意义；依循；实行；沿着；追究；正确", "susu"},
            {"包(红白)钱", "cemavu"},{"选举", "sinkiu"},
            {"烘烤", "cemapa"},{"怀念；思念", "singlit"},
            {"刨木", "cemvak"},{"家名", "sapai"},
            {"阉割", "cemviq"},{"很臭", "sasequsequ"},
            {"给某人盖被子", "cemauv"},{"羡慕", "saljinga"},
            {"不舒服", "sarukuya"},{"寄送", "semusuq"},
            {"再来一次", "siumaumalj"},{"落单", "sepakacidilj"},
            {"职业", "sengsengan"},{"扇子", "sipaizan"},
             //d
            {"仰慕", "djalim-"}, {"大腿", "djapalj"},
            {"趴着", "djeljapa"}, {"含有铁锈的水", "djerav"},
            {"全身沾有血迹", "djamudjamuqan"}, {"被…打", "djukulen"},
            {"湿滑", "dalut"}, {"亲近", "djadjeljek"},
            {"额头", "djaqis"}, {"脚步", "djekuac"},
            {"舔", "djiljing-"},{"悬崖", "dangadangas1"},
            {"曾用手抓(食)", "djinakuc"}, {"请你吹起…", "djapesu"},
            {"蛀牙", "djekecan1"}, {"菜盘", "dunbuli"},
            {"招来", "djaulj-"}, {"挑衅", "djaulj-"},
            {"屋墙", "djeljep"}, {"悬崖", "djerapalj"},
            {"黏土", "djumulj"}, {"罹患", "djekecan"},
            {"正在浇水", "djemiqedjiqes"}, {"电", "dingki1"},
            {"腌制", "djaung"}, {"弄脏", "djemekec"},
            {"刺", "djui"}, {"红藜", "djulis"},
            {"拿着", "djemadjas"}, {"揉成一束", "djemaljeng"},
            {"招来", "djemaulj"}, {"舔", "djemiljing"},
            {"第二个", "djaljedalj"}, {"接续", "djaljedalj"},
            {"血", "djamuq"}, {"榕树叶", "djaraljap"},
            {"摸", "djivic-"}, {"可拿到", "djivic-"},
            {"刺球竿", "djuljat"},{"用手拿", "djakucen"},
            {"原来如此", "daljepan"}, {"所走過的", "djinavacan"},
            {"被堆积的", "djinumulj"}, {"怒气", "duduan"},
            {"用手拿取", "djakuc-"}, {"抓到", "djameq-"},
            {"逮捕", "djameq-"}, {"准备", "djele-"},
            {"水藻", "djepelang"}, {"被逮捕", "djinameq"},
            {"有刺的", "djuidjuian"}, {"有荆棘的", "djuidjuian"},
            {"正在堆放", "djemumudjumulj"}, {"达成", "djaljun-"},
            {"到达", "djaljun-"},{"成就", "djaljun-"}, 
            {"破晓时分", "djama-"},{"针", "djaum"},
            {"棍子", "djukul"}, {"被打", "djukul"},
            {"充电", "djuling-"}, {"在刺球", "djumuljadjuljat"},
            {"铲平", "duviduv"}, {"木耳", "djarunuq"},
            {"走路", "djavac"}, {"走路", "djavac"},
            {"让路", "djavac"},{"以步伐测量", "djavac"},
            {"高处的..物品", "djivic1"},{"手气好的男人", "djuljam"},
            {"容易", "djulu-"}, {"编制", "demangas"},
            {"正在走路", "djemavadjavac"}, {"令人发怒", "deminudu"},
            {"残屑", "dengec"}, {"黑人", "duzing"},
            {"月經", "djaq"}, {"锅巴", "djekec"},
            {"痰", "djilai"}, {"馘首", "djemulu"},
            {"修篮子(编制品)边缘", "demangadangas"},
            {"请你抓", "djakucu"}, {"捞", "djakucu"},
            {"请你务必到达某地或与某人所在之处", "djaljunuanga"}, {"辛苦了", "djavadjavai"},
            {"微笑", "djemelidjeli"}, {"触的到", "djivicen"},
            {"预设的目标", "djivicen"}, {"四脚蛇", "djadjiljaq"},
            {"九芎树", "djaqas"}, {"腳印", "djekap"},
            {"屁股", "djilj"}, {"堆", "djumulj"},
            {"贴膏", "djupil"}, {"下雨滴", "demalek"},
            {"用手抓", "djemakuc"}, {"同伴", "djadjalan"},
            {"到达", "djemaljun"}, {"吹着", "djemapes"},
            {"笑", "djemeli"}, {"土密树", "dangas-"},
            {"路", "djalan"},{"道路", "djalan"},
            {"马路", "djalan"},{"吹着", "djapes"},
            {"吹起", "djapes"},{"吹气", "djapes"},
            {"感谢", "djavai1"},{"进展", "djavai1"},
            {"辛苦了", "djavai1"},{"浇水", "djiqes-"},
            {"近", "dedet1"},{"抓到", "djemameq"},
            {"走路", "djemavac"},{"曾经被打", "djinukul"},
            {"请堆", "djumulju"},{"水滴", "dalek"},
            {"露水", "dalek"},{"边缘", "dangas-1"},
            {"悬崖", "dangas-1"},{"托付", "djadjas-"},
            {"摸着", "djadjas-"},{"抚摸", "djaqup-"},
            {"砍草", "demangdang"},{"菜肴", "djamai"},
            {"笑", "djeli"},{"颈链", "djegel"},
            {"怒气", "dudu-"},{"生气", "dudu-"},
            {"惹怒", "dudu-"}, {"幸好", "daqai-"},
            {"乡民代表", "daihiu"}, {"安抚", "djaqupen"},
            {"被舔舐", "djiljingan"}, {"请你抓着", "djadjasu"},
            {"好表现", "daudavan"}, {"吃完", "djemdjem-"}
            {"被吃掉", "djemdjem-"}, {"靠近", "det"},
            {"浇水", "djemiqes"}, {"吐痰", "djemilai"},
            {"被吹了", "djinapes"}, {"达成", "djaljunen"},
            {"近亲", "dedet"}, {"把草砍光", "dangdangu"},
            {"陶瓮", "djilung"}, {"对不起", "djavai2"},
            {"男子名", "djaulj"}, {"螺丝起子", "dulaiba"},
            {"开垦新地", "daudav-"},{"正在舔", "djemiljidjiljing"},
            {"摸脸", "djemaqup"},{"配菜", "djemamai"},
            {"已经砍干净了", "dinangdangananga"},{"黏着剂", "djukic"},
            {"死亡", "djaung"},{"菜肴", "djamai-"},
            {"吃菜", "djamai-"},{"做菜", "djamai-"},
            {"适合", "djaljep-"},{"一把", "djaljeng-"},
            {"揉成", "djaljeng-"},{"电灯", "dingki"},
            {"桌子边缘", "dangadangas"},{"溶化", "djerenav-"},
            {"黏", "djekec-"},{"摸的到", "djemivic"},
            {"请你拿下来", "djivicu"},{"编制", "dangas"},
            //dj
            {"具有｢仰慕｣之意", "djalim-"},{"大腿", "djapalj"},
            {"趴着", "djeljapa"},{"全身沾有血迹", "djamudjamuqan"},
            {"被…打", "djukulen"},{"亲近", "djadjeljek"},
            {"额头", "djaqis"},{"脚步", "djekuac-"},
            {"具有｢舔｣之意", "djiljing-"},{"曾用手抓(食)", "djinakuc"},
            {"请你吹起…", "djapesu"},{"蛀牙", "djekecan 1"},
            {"具有｢招來、挑釁｣之意", "djaulj-"},{"屋墙", "djeljep"},
            {"悬崖", "djerapalj"},{"正在浇水", "djemiqedjiqes"},
            {"黏土", "djumulj"},{"具有｢腌制…｣之意", "djaung"},
            {"罹患", "djekecan"},{"弄脏", "djemekec"},
            {"刺", "djui"},{"招来", "djemaulj"},
            {"红藜", "djulis"},{"舔", "djemiljing"},
            {"拿着", "djemadjas"},{"具有｢吃完、吃光光、被吃掉｣之意", "djemdjem-"},
            {"揉成一束", "djemaljeng"},{"请你抓着", "djadjasu"},
            {"安抚", "djaqupen"},{"月经", "djaq"},
            {"被舔舐", "djiljingan"},{"锅巴", "djekec"},
            {"等要浇水", "djadjiqesen"},{"痰", "djilai"},
            {"充电", "djemuling"},{"馘首", "djemulu"},
            {"请你抓;捞", "djakucu"},{"辛苦了", "djavadjavai"},
            {"请你务必到达某地或与某人所在之处", "djaljunuanga"},{"微笑", "djemelidjeli"},
            {"触的到；预设的目标", "djivicen"},{"屁股", "djilj"},
            {"趴四脚蛇着", "djadjiljaq"},{"堆", "djumulj"},
            {"九芎树", "djaqas"},{"贴膏", "djupil"},
            {"脚印", "djekap"},{"用手抓", "djemakuc"},
            {"同伴", "djadjalan"},{"到达", "djemaljun"},
            {"吹着", "djemapes"},{"笑", "djemeli"},
            {"具有｢达成、到达、成就｣之意", "djaljun-"},{"具有｢破晓时分｣之意", "djama"},
            {"针", "djaum"},{"棍子;被打", "djukul"},
            {"具有｢充电｣之意", "djuling-"},{"在刺球", "djaljedalj"},
            {"第二个;接续", "djumuljadjuljat"},{"血", "djamuq"},
            {"榕树叶", "djaraljap"},{"所走过的", "djinavacan"},
            {"刺球竿", "djivic"},{"被堆积的", "djinumulj"},
            {"用手拿", "djuljat"},{"具有｢拿着、摸着、托付｣之意", "djadjas-"},
            {"第二个;接續", "djakucen"},{"具有｢抚摸｣之意", "djaqup-"},
            {"具有｢以步伐量距｣之意", "djekuac-"},{"具有｢黏｣之意", "djekec-"},
            {"表示溶化之意。针", "djerenav-"},{"请你拿下来", "djivicu"},
            {"吹起来", "djapesen"},{"木耳", "djarunuq"},
            {"摸的到", "djemivic"},{"走路；走过；让路；以步伐测量血", "djavac"},
            {"高处的..物品", "djivic"},{"具有｢用手拿取｣之意", "djakuc-"},
            {"手气好的男人", "djuljam"},{"具有｢抓到、逮捕｣之意", "djameq-"},
            {"具有｢容易｣之意", "djulu-"},{"具有｢准备、为…而准备｣之意", "djele-"},
            {"正在走路", "djemavadjavac"},{"水藻", "djepelang"},
            {"被逮捕", "djinameq"},{"笑；笑声", "djeli"},
            {"有刺的;有荆棘的", "djuidjuian"},{"菜肴", "djamai"},
            {"正在堆放", "djemumudjumulj"},{"正在吹起", "djemapedjapes"},
            {"颈链", "djegel"},{"用水…", "djiqesen"},
            {"具有｢一束、一把、揉成…｣之意", "djaljeng-"},{"黏着剂", "djukic"},
            {"具有｢适合｣之意", "djaljep-"},{"配菜", "djemamai"},
            {"具有｢菜肴、吃菜、做菜｣之意", "djamai-"},{"摸脸", "djemaqup"},
            {"具有｢死亡｣之意", "djaung"},{"刺球场", "djadjuljatan"},
            {"刺球", "djemuljat"},{"达成", "djaljunen"},
            {"男子名", "djaulj"},{"被吹了", "djinapes"},
            {"对不起；抱歉之意", "djavai"},{"吐痰", "djemilai"},
            {"陶瓮", "djilung"},{"浇水", "djemiqes"},
            {"路;道路;马路", "djalan"},{"具有｢吹着、吹起、吹气｣之意", "djapes"},
            {"感谢；进展；辛苦了", "djavai"},{"具有｢浇水｣之意", "djiqes-"},
            {"抓到", "djemameq"},{"走路", "djemavac"},
            {"曾经被打", "djinukul"},{"请堆", "djumulju"},
            //dr
            {"吶", "dra"},{"锻炼屋", "lalangan"},
            {"长；高", "laruq"},{"丧礼肩巾", "lepec"},
            {"女子名", "liljuk1"},{"聘禮", "lisi"},
            {"具有｢闹脾气、小气、捉弄人｣之意", "luqic-"},{"荣耀礼", "ljakarav"},
            {"昭和草", "ljaluing"},{"具有｢探访、温馨、解脱｣之意", "ljav-"},
            {"流感", "ljayar"},{"针", "ljigim"},
            {"長；高", "ljuku"},{"具有｢能吃｣之意", "ramilj"},
            {"具有｢仰头｣之意", "reqang-"},{"马", "rigi"},
            {"弯", "rukung"},{"避开", "lemagav"},
            {"捕捉", "lemala"},{"下坡", "ljelauz"},
            {"唱哀歌", "ljemayuz"},{"不受肯定", "lumaljen"},
            {"撼动", "lemegeleg2"},{"交界；边界", "ljaljaqedian"},
            {"中文", "ljinautjian"},{"败坏", "rupaqatelengan"},
            {"正在台风", "remaljiraljiz"},{"爱吃醋的", "rukarengec"},
            {"说日语", "remipungan"},{"收拾；储藏", "remukuz"},
            {"抓进监狱", "remusung"},{"高地的", "ljaizaya"},
            {"女子名", "dremedreman"},{"连杯", "langalj"},
            {"具有｢连杯、向后仰、躺、仰卧｣之意", "langalj"},{"具有｢赐予｣之意", "lavut"},
            {"具有｢自立、竖立、设立、站立｣之意", "lingdjelj-"},{"砖头", "lingga"},
            {"具有｢松｣之意", "luka-"},{"口琴", "ljaljegean"},
            {"冷", "ljaljeqel"},{"晒；使…曝晒；日晒", "rasi"},
            {"万寿菊", "ljangi"},{"具有｢和解｣之意", "rengec"},
            {"腋下", "ljeqeljeqan"},{"具有｢皱纹｣之意", "rengec"},
            {"猫头鹰", "ljequ"},{"具有｢醋劲｣之意", "lavut"},
            {"具有｢瞪、斜眼｣之意", "ljiqedev-"},{"具有｢滚动｣之意", "ruqu-"},
            {"蜡烛", "rusuku"},{"逗笑", "ljiquin"},
            {"正在吞", "lemamelamedj"},{"放在摇篮里", "ljemiug"},
            {"光榮", "lemigu"},{"惹使生气；捉弄人", "lemuqic"},
            {"去敬酒", "ljagayu"},{"分給", "lemuvad"},
            {"议题", "ljavaran"},{"分…給…", "luvadan"},
            {"苍蝇", "lalangaw"},{"催促", "remucruc"},
            {"烫伤；因烫伤脱皮", "laqut"},{"尖的", "ruadjuadjum"},
            {"老板", "laupan"},{"二元", "rusavatan"},
            {"桑葚", "liljuk2"},{"专采无患子的人", "rukizaqu"},
            {"脖子", "liqu"},{"二", "drusa"},
            {"多话；健谈", "rukai"},{"具有｢阻碍、懒惰｣之意", "lupi-"},
            {"畏惧", "regem-1"},{"守护神", "ljaljumegan"},
            {"具有｢故意、自作自受、捉弄｣之意", "ranav-"},{"手腕", "ljakaljat"},
            {"茅草(建筑用的)", "ravuc"},{"具有｢清楚、瞭解｣之意", "ljaluai-"},
            {"具有｢开玩笑｣之意", "ljikai-"},{"嘴唇", "ljelet"},
            {"有爱心", "rukiljivakan"},{"匍匐", "ljemaljap"},
            {"闪电", "lemadjap"},{"讲中文", "ljemautjian"},
            {"捕捉的", "linalan"},{"温馨", "ljavljavan"},
            {"连杯", "langalj"},{"捡到的", "ljinulju"},
            {"满溢；溢出来", "lemiav"},{"卷起", "lemutlut"},
            {"装在篮子里", "rinakuyan"},{"叉", "rinavuc"},
            {"用茅草盖的", "rinakuyan"},{"女子名", "dresdres"},
            {"弯曲", "rukurukung"},{"多排琉璃项链(3-5排)", "drinpa"},
            {"领唱者", "rusenasenai"},{"具有｢避开、回避、遗忘｣之意", "lagav-2"},
            {"下來", "ljeteku"},{"捲起", "lemutlut"},
            {"使变成…", "ljeme-"},{"满溢", "laviq-"},
            {"南瓜", "ljasiak"},{"苎麻绳、一捆(特指小米)", "lekelek"},
            {"具有｢交界、边界、邻居｣之意", "ljaqedi-"},{"女子名", "lingac"},
            {"瘀青", "ljanger"},{"立法委员", "lipuiing"},
            {"男子名", "ljagai"},{"痛；痛苦；承受痛苦；喊痛", "lutud"},
            {"韧带", "rekec"},{"火种", "ramac"},
            {"具有｢垮、拆毁｣之意", "revur-"},{"锋利的", "radjai"},
            {"用石头堆砌；石墙", "rumul"},{"瓶盖;堵塞", "ljupetj"},
            {"诈骗集团", "rubulubulung"},{"祭仪", "ljeveq-"},
            {"远离一点", "ljiacadjau"},{"看见", "ljengljeng-"},
            {"锹形虫", "ljaqecaqecap"},{"轻视；鄙视", "ljememet"},
            {"懒散", "lupilupi"},{"阴凉处", "ljaung"},
            {"拾取", "ljemulju"},{"庇护", "ljemakev"},
            {"瞪", "lemiqeliqedev"},{"切菜", "ljemaceng"},
            {"烧动物的毛", "ljemengis"},{"未经嚼食即吞咽", "lemqes"},
            {"利用晚间", "remaqezemetj"},{"答应了", "ljemaui"},
            {"被拉", "rinakac"},{"面粉", "lamug"},
            {"晒谷场", "rarasian"},{"腰带", "ledeled"},
            {"一拐一拐", "remialan"},{"西方", "ledep-"},
            {"弄弯曲的", "rinukung"},{"猜谜", "liguligu"},
            {"棺木", "lukulj"},{"假酸浆", "ljavilu"},
            {"一一的", "ljemita"},{"起水泡", "ljetiq-"},
            {"具有｢调整、修理、舒适｣之意", "ljenguaq-"},{"逗趣", "ljiqu"},
            {"小指头", "rusenasenai"},{"壳", "rariq"},
            {"男子名", "ljaljeqelan"},{"阻栏", "rengez"},
            {"颈链", "reqel"},{"六月", "rukacu"},
            {"表示一个单位", "ringuc"},{"吞食", "lemamedj"},
            {"经常欺骗", "lukugacu"},{"常拿(隐喻偷窃)", "rualap"},
            {"假神", "ruburu"},{"煮", "ruljaqljaqan"},
            {"六月", "ljacemacemas"},{"很容易被逗笑", "ruljaqljaqan"},
            {"烧热水、滚水", "lalja-"},{"捉弄", "ranaven"},
            {"钝钝的", "runpenpenl"},{"探视", "ljemizaw"},
            {"冲洗(特指地瓜和竽头)", "remugrug"},{"倦怠", "luljaluljai"},
            {"尖尖的", "rudjudjum"},{"正摇动", "ljemiuljiug"},
            {"促使和平", "remasudj"},{"训勉", "ljemavaran"},
            {"灰烬", "lavu"},{"露珠", "ljadjek"},
            {"摇动、震动、撼动", "legeleg-"},{"扫帚", "ljaljumai"},
            {"豹", "likuljav"},{"对话、文告、议题、训勉、造谣", "ljavar-"},
            {"隔间", "livek"},{"轻视、被鄙视", "ljemet-"},
            {"具有｢分配｣之意", "luvad-"},{"甩干", "ljiak-"},
            {"文株兰", "ljivakung"},{"常打鼾", "ruvarequn"},
            {"具有｢偷情、劈腿｣、分叉之意", "raqa"},{"热水", "linalja"},
            {"怕、胆小、敬畏", "rekutj-"},{"细的", "linedje"},
            {"陶壶(有雕纹的)", "reretan"},{"常生气的", "rulimuceng"},
            {"具有｢尖｣的意思", "rudjum-"},{"雨具", "ljaung"},
            {"河岸", "ljemavingan"},{"时常缺课", "rupulavai"},
            {"逗乐", "ljemiqu"},{"使...晒", "remasi"},
            {"放低身体", "ljemaljukuan"},{"胆小鬼", "rurekutjan"},
            {"使成熟", "lemum"},{"短的", "rikirikitj"},
            {"扳着脸;不喜欢；生气", "limuceng"},{"被…滚动", "rinuqu"},
            {"绿", "liljuas"},{"前小腿", "ljungudan"},
            {"用茅草盖的", "litengic"},{"具有｢乍现｣之意", "ljimamur-"},
            {"板着脸", "rukurukung"},{"喜泣之歌", "ljayuz"},
            {"具有轻视、经不起之意", "luqem-"},{"发音近似中文老爹；意指汉人；汉人(另称外省人)", "ljautjia"},
            {"眼泪", "luseq"},{"痕迹", "ljatel"},
            {"耆老", "ramaljeng"},{"记录", "ruku-"},
            {"树枝", "ricing"},{"常偷", "rucakav"},
            {"礼拜", "rihai"},{"叉形", "draqadraqa"},
            {"困惑", "rucruc"},{"亲密朋友", "dravadrava"},
            {"摇动", "lemegeleg1"},{"手伸入洞穴里", "lemutlut"},
            {"正在生气", "limucemuceng"},{"邻居", "ljaqediqedi"},
            {"包围", "lemingulj"},{"使人喪氣", "lemumalj"},
            {"冷了", "ljaljeqeljeqel"},{"性欲强烈", "ruqazimanan"},
            {"游泳", "ljemangui"},{"照顾", "remapalj"},
            {"爬上", "remaqiz"},{"鼾声", "drequng"},
            {"请你…滚…", "ruquu"},{"女性朋友", "drava"},
            {"禁闭室", "rarusungan"},{"靠左边一点", "ljiaviri"},
            {"获…准", "ljinaui"},{"不诚实", "ruveca"},
            {"闪电", "ladjap"},{"智慧、智者、急促、时间", "lingav-"},
            {"短暂、过份、允许", "lamu-"},{"六", "luku"},
            {"凹陷；低洼", "likeljung"},{"匍匐前进", "ljaljap-"},
            {"木汤盆", "lingadja"},{"游泳、戏水、游泳池(地方)", "ljangui-"},
            {"玉米", "ljapanai"},{"櫛芒(芒草)", "ljavia"},
            {"桑树", "ljisu"},{"陷阱", "ringai"},
            {"勇士", "rakac"},{"工具钝了", "runpel-"},
            {"篮子", "rakui"},{"具有沾到之意", "rupaq-"},
            {"关节种称", "raregeregan"},{"荣幸", "levan"},
            {"低洼的", "likeljukeljung"},{"置于棺木", "lukuljen"},
            {"敬酒", "ljemagai"},{"請分", "lemuqem"},
            {"正在敬酒", "ljemaluai"},{"经常迟疑", "rupaivatjan"},
            {"瞭解", "rusenasenai"},{"忍耐", "rukiqadilj"},
            {"每年", "ljemitacavilj"},{"伍堆", "limaaqepuan"},
            {"猪", "dridri"},{"兔子", "lutjuk"},
            {"球蕨", "lavucuvucu"},{"青菜；野菜", "ljaceng"},
            {"肋骨、嫩、细、鲜嫩", "ledje-"},{"清澈", "ljamecav"},
            {"手", "lima"},{"逗趣、逗笑", "ljaqljaq-"},
            {"风闻；抱怨或微词", "ljeminga"},{"台风", "raljiz"},
            {"听觉；专注倾听", "ljiabar"},{"具有｢对温度的感受｣之意", "regem"},
            {"漏斗", "ljutu"},{"具有｢鼾声｣之意", "requng"},
            {"鸭子", "raimai"},{"高梁", "rumagai"},
            {"兽栏", "ruvu"},{"瞪", "lemiqedev"},
            {"听到", "lemangda"},{"低着头", "ljemuku"},
            {"阴凉处树荫", "ljauljaung"},{"好命", "rupuqimangan"},
            {"修理；弄好；整理", "ljemenguaq 1"},{"晒了", "rinasi"},
            {"忘记", "remauraw"},{"锋利的", "radjai"},
            {"阻挡", "remengez"},{"垮、拆毁", "revur-"},
            {"拆除", "remevur"},{"诈骗集团", "rubulubulung"},
            {"关入兽栏", "remuvu"},{"远离一点", "ljiacadjau"},
            {"风闻；抱怨或微词", "ruvaik"},{"低头；垂头丧气", "remequng"},
            {"被关入监狱", "ruvaik"},{"容易生气", "lumalumalj"},
            {"答应吧", "rinusung"},{"修理", "ljemenguaq"},
            {"常出去", "raimai"},{"正在烧猪毛", "ljemengiljengis"},
            {"用披肩包裹", "lemipelip"},{"使蹲姿", "likuculjen"},
            {"砖造的", "liningga"},{"具有｢孕育、储藏、存放、包｣之意", "rukuz-"},
            {"急促(尿急);时间", "lingav"},{"男子名", "ripun"},
            {"烧水之处或器皿", "lalaljan"},{"将手放置腰后", "rikul"},
            {"软", "lumeljak"},{"专指收割后遗漏的稻穗", "lagav"},
            {"炉灶", "likezalj"},{"青铜刀总称", "dragaman"},
            {"愚蠢", "levlev"},{"鲁凯族", "rekaizuku"},
            {"烤窑", "leku"},{"繁复", "rimuan"},
            {"一跛一跛", "rial-"},{"黄牛", "ljuang"},
            {"信靠、依靠、托付、交托", "rangez-"},{"边缘", "ljaving"},
            {"芋头粉", "ragrag"},{"具有｢掌管、管辖｣之意", "ljavak-"},
            {"骨髓", "ljuseq"},{"刺茄", "ljasaras"},
            {"贪心之人", "ruqaravanan"},{"很会惹事", "rupitiqan"},
            {"靠这一边；靠过来", "ljaimaza"},{"小气", "luqiluqic"},
            {"看清楚", "ljemengljeng"},{"游泳池(地方)", "ljaljanguyan"},
            {"弄坏", "ljemekuya"},{"用手制成的", "linima"},
            {"长舌妇", "rukaikai"},{"电话", "ljingas"},
            {"监狱", "rusung"},{"靠南方之处(也称靠近平坦之地)", "ljavljav"},
            {"虾笼", "rumuk"},{"疤痕", "ljaqic"},
            {"笔茼树", "rikis"},{"生姜", "ljamljam"},
            {"但是", "ljakua"},{"肃静", "liceng"},
            {"水果成熟", "lum"},{"听、听话、听到", "langda-"},
            {"圆形", "lipuru"},{"确认", "dri"},
            {"伙伴；陪伴", "lingulj"},{"五元", "limavatan"},
            {"多；多次；太多；满溢", "liav"},{"下聘", "lemisi"},
            {"猴子", "ljavingan"},{"辛劳", "luljayan"},
            {"音质；声音", "ljingav"},{"历史", "likisi"},
            {"嫩", "ledjeledje"},{"巫师问卜用之壶", "ljui"},
            {"收拾；储藏", "remukuz"},{"凌晨", "ljia"},
            {"飞鼠", "lava"},{"同性朋友(女朋友)", "rava"},
            {"传统服饰", "ravaravain"},{"蜈蚣", "ljaljiga"},
            {"恐惧害怕", "rekutjan"},{"玛瑙珠", "drimukui"},
            {"乐于服役", "rukisekaulj"},{"烧", "ljengis"},
            {"秋蝉", "ljaljai"},{"头晕", "lingac"},
            {"混浊", "ljimek"},{"悲悯之心", "rusaleljeseljan"},
            {"具有｢用拳头打、揍人｣之意", "rumul-"},{"(古壶)月亮的眼泪", "luseqnaqiljas"},
            //e
            {"穿大衣", "emuba"}, {"男子名", "esai"},
            {"女子名", "eme"}, {"男子名", "ege"},
            {"女子名", "ekes"}, {"女子名", "eleng"},
            {"女子名", "epe"}, 
            //g
            {"鹅", "gaciu"}, {"咬牙切齿", "galjecegec"},
            {"电石", "gasu"}, {"瓦斯", "gasu"},
            {"惧怕", "giljic-"}, {"五指尖交错", "gumec"},
            {"站立", "gemacalj"}, {"站立", "gacalj-"}
            {"起身", "gacalj-"}, {"斯文", "galju-"},
            {"缓慢", "galju-"}, {"犹如陶壶之意", "giljugiljung"},
            {"牛", "gung"}, {"搔头", "garucgucguc"},
            {"不智的决定", "gunggungan"}, {"痒", "gacel"},
            {"长辈所属意的人", "galju"}, {"议论", "gilun"},
            {"龙眼", "gingging"}, {"爪", "gumac"},
            {"请你拨开", "gucalu"},{"轰隆隆的声音", "galugulugu"},
            {"长排椅子", "garaljigalj"},{"咆哮", "giring-"},
            {"吠", "giring-"},{"取消", "gula"},
            {"放弃", "gula"},{"暂停", "gula"},
            {"被…抓", "gumacen"},{"男子名", "gagang"},
            {"含羞草", "gagumuc"},{"议长", "giciu"},
            {"边", "gidi-"},{"旁边", "gidi-"},
            {"牛车", "giusia"},{"乡镇", "gu"},
            {"被取消", "ginula"},{"女子名", "galaigai"},
            {"灵力", "garang"},{"精神", "garang"},
            {"不想跟去", "garang"},{"狗吠", "gemiring"},
            {"咆哮", "gemiring"}, {"鞭子", "guzui"},
            {"五月", "gugacu"}, {"咆哮", "gemirigiring"},
            {"放弃", "gulain"}, {"正被鞭打", "guzuguzuin"},
            {"吵", "galugu"}, {"青铜刀(小把)", "gaus"}
            {"搅乱", "guraruc-"}, {"护士", "gusi"},
            {"慢走", "galjugaljuu"}, {"一路平安", "galjugaljuu"},
            {"被…搅动", "ginuraruc"}, {"狗吠声", "gemurugur"},
            {"危险", "gagalj-"}, {"惧怕", "gagalj-"},
            {"勤劳", "gamel"}, {"合唱", "gasiu"},
            {"议员", "giʼing"}, {"船舰", "gungkang"},
            {"使…痒", "gemacel"},{"很令人厌恶", "gemaljecegec"},
            {"刮除芋头皮动作", "gemilegil"},{"叫喊", "gemugu"},
            {"癌症", "gang"},{"肿瘤", "gang"},
            {"胸腔", "garunggungan"},{"垫脚", "gisilj-"},
            {"小米种类之一", "gumac"},{"爪", "gumac"},
            {"抓", "gumac"},{"捏人", "gemcel"},
            {"沿着…边", "gemidigidian"},{"暂停", "gemula"},
            {"被抓", "ginumac"},{"学校", "gakku"},
            {"议案", "gian"},{"拨开", "gucal-"},
            {"搔痒", "gucguc"},{"搔痒器具", "gucguc"},
            {"持续不断", "gemedeged"},{"塌陷", "geluyuc"},
            {"塌下来", "geluyuc"}, {"乡公所", "gukusiu"},
            {"轰隆声", "galjungegung"}, {"瓦斯", "gasu"},
            {"塑胶", "gumu"}, {"橡皮筋", "gumu"},
            {"笨", "gunggung"}, {"山丘", "gadugadu"},
            {"连连发轰隆声", "galjungegungegung"}, {"最旁边", "gidigidian"},
            {"月历", "gacu"}, {"山", "gadu"},
            {"气愤", "galemegem"}, {"持续", "gedged"},
            {"频繁", "gedged"}, {"议会", "gikai"},
            {"男子名", "giljegiljaw"}, {"起床", "gacalju"},
            {"危险", "gemagalj"}, {"遇到鬼", "ginalalj"},
            {"去皮的芋头", "giniljegilan"},{"乡长", "guciu"},
            {"拨开", "gemucal"},{"好动", "garavagav"},
            {"梳子", "garuc"},{"梳", "garuc"},
            {"握紧拳头", "gemgem-"},{"闹鬼", "gemalalj"},
            {"频繁", "gedgeden"},{"命令狗吠", "guruguru"},
            {"被鞭打过", "ginuzui"},{"家名", "gadu"},
            {"鬼", "galalj"},{"去皮", "gilgil-"},
            {"男子名", "gisilj"},{"叫", "gugu"},
            {"沿山的", "gemaduan"},{"靠山的", "gemaduan"},
            {"需拨开", "gagucalen"},{"搔痒", "gemucguc"},
            {"亮晶晶", "galiljegilj"},{"螃蟹螯", "gecel-"},
            {"捏", "gecel-"}, {"被捏", "gecel-"},
            {"技术", "giziucu"}, {"技艺", "giziucu"},
            {"疙瘩", "gulu-"}, {"很危险的", "geminagalj"},
            {"被捏", "ginecel"}, {"被拨开", "ginucal"}
            {"被狗吠", "guruguren"}, {"狗吠", "gurugur-"},
            {"迟缓", "gemalju"}, {"螃蟹螯", "gecel"},
            {"紧握着", "gemgemen"}, {"抓起", "gemumac"},
             //h
            {"方向盘", "handuru"}, {"皇帝", "huangti"},
            {"法院", "huing"}, {"八月", "hacigacu"},
            {"方向盘似的玩具", "handuruduru"}, {"飞机", "hikuki"},
            {"广播器", "husu"}, {"博士", "hakasi"},
            {"哈利路亚", "haliluya"}, {"信封袋", "hutu"},
            {"手帕", "hangkaci"}, {"小锅子", "hanggu"},
            {"赤脚", "hadasi"}, {"汽车", "haya"},
            {"选票", "hiyu"}, {"盒子", "haku"},
            {"执事", "hicuzi"}, {"秘书", "hisiu"},
            {"法律", "hulic"}, {"花子(日本女子名)", "hanako"},
            {"表决", "hiukicu"},{"妇女会长", "huzinkaiciu"},
            {"妇女会", "huzinkai"},{"报告", "hukuku"},
            {"口琴", "hamunika"},{"肺结核", "haikikaku"},
            {"装在盒子", "hakuhaku"},{"花", "hana"},
            {"印章", "hang"},{"反对", "hantai"},
            
            //i
            {"肥皂", "iuku"}, {"如此", "inayatucu"},
            {"用石头堆砌的…", "inupuan"}, {"这个", "icu"},
            {"我们", "itjen-"}, {"在旁边", "igidi"},
            {"更名", "inumalj"}, {"尿液", "isiq"},
            {"野菜", "yasai"}, {"在那儿", "inu"},
            {"不符合", "inikapacengceng"}, {"不对称", "inikapacengceng"},
            {"烟囱", "intucu"}, {"幼稚园幼童", "yucing"},
            {"预算", "yisuan"}, {"一百", "itaidai"},
            {"一万", "itakurav"}, {"无止境", "iputjatjeketjekan"},
            {"耳垢", "iluq"}, {"邮政局", "yubinkiuku"},
            {"不行", "inika-"},{"不对", "inika-"},
            {"不良", "inika-"},{"笔", "inpic"},
            {"一月", "icigacu"},{"在学校", "igakku"},
            {"行为不良", "inikananguaq"},{"居住环境不方便", "inikanaseljenguaq"},
            {"沿山公路", "yinsankunglu"},{"拿去了", "inalap"},
            {"衣服", "itung"},{"传统服", "itung"},
            {"洗石子", "isi"},{"男用上衣", "ibuk"},
            {"尾巴", "iku"},{"当日", "ivuavuaq"},
            {"青蛙", "iav"},{"最后一名", "ikuikuan"},
            {"不对", "inikaparia"},{"在这里", "imaza"},
            {"卫生所", "isisiu"},{"棒球", "yakiyu"},
            {"枝叶末端", "ingav"}, {"祈祷", "inuli"},
            {"在附近", "idedet"}, {"碗内", "itakisi"},
            {"一元", "itavatan"}, {"反对", "ini-"},
            {"羊", "iu"}, {"椰子", "yasi"},
            {"在外面", "icasav"}, {"何处", "iainuan"},
            {"一千", "itakuzulj"}, {"不好看", "inikanguanguaq"},
            {"美语", "inamilikan"}, {"不是", "ini"},
            {"差一点", "isai"}, {"耶稣", "yisu"},
            {"遗留", "inadjuq"}, {"祷告会", "inulikai"},
            {"在教会", "ikiukai"}, 
            //k
            {"男用小腰袋", "kadrai"},{"植物名", "kaladju"},
            {"特别准备", "kaljava"},{"鱼罐头", "kanzumi"},
            {"爬槟榔用脚套绳", "katjung"},{"免费", "kavutan"},
            {"麻雀", "kerilj"},{"家鼠", "kiki"},
            {"托腮", "kitaqmez"},{"卫生棉", "kucip"},
            {"细", "kuljai"},{"公司", "kusi"},
            {"敌人", "qalja"}, {"仇人", "qalja"},
            {"下腹部", "qamudru"}, {"女性私处", "qamudru"},
            {"鹅卵石", "qararat"}, {"跳蚤", "qatimtim"},
            {"肩膀", "qavan"}, {"阻挡", "qeceng-"},
            {"狭窄", "qelicing"}, {"闭口", "qeljetep"},
            {"痰", "qesang"}, {"感冒", "qesang"},
            {"候鸟", "qiciqic"}, {"部落", "qinaljan"},
            {"萤火虫", "qucivauvaw"}, {"吉丁虫", "quljimamarav"},
            {"白发", "quras"}, {"喂养", "quzip-"},
            {"养育", "quzip-"}, {"真诚", "kemalja"},
            {"穿着上衣", "kavan"},{"了解", "kemeljang"},
            {"眼皮一直跳", "kaljidkid"},{"立仓储", "kemubaw"},
            {"踩高跷", "kemulakula"},{"撕破", "kuyain"},
            {"四周", "kipalingulj"},{"冬天", "kaljaljaljeqelan"},
            {"更早", "kiljuvaq"},{"承受痛", "kilutulutud"},
            {"想法", "kininemeneman"},{"平坦", "kasinguaq"},
            {"未婚入夫家的女孩", "kiparuk"},{"有力的", "katjepiculan"},
            {"用垫子垫脚", "kipuqapudju"},{"戴雄鹰羽毛", "qemadris"},
            {"夹着", "qemaljapitj"},{"滚翻", "kiqaluresing"},
            {"跨坐", "kiqaraqar"},{"珠珠", "qataqata"},
            {"大声呼救", "qemauqav"},{"检查", "kiqayam"},
            {"生蛋", "qemecilu"}, {"关起门", "kiqeljev"},
            {"磨成粉", "qememu"}, {"召集了", "qinepuqepu"},
            {"正在感冒", "qemsaqesang"}, {"正在咳嗽", "qemsaqesang"},
            {"被熄灭", "qinevutj"}, {"正月", "kaqiljasan"},
            {"沾有泥土", "qipuqipuan"}, {"黄色的", "qulivalivai"},
            {"猎首", "kiqulu"}, {"外遇", "kiraqa"},
            {"自残", "kipasaqetju"}, {"骑在…之上", "kisevalj"},
            {"吹风", "kivali"}, {"纳凉", "kivali"},
            {"跟随随后", "kitjavililj"}, {"赞美", "kemazala"},
            {"瞳孔", "kakakaka"}, {"耙", "kakara"},
            {"深地", "kalicekuan"},{"梅雨季节", "kaliman"},
            {"篮子(腰篮)", "karangu"},{"碎布", "karari"},
            {"百合花", "kavaluan"},{"屋瓦", "kavara"},
            {"欠", "kiam"},{"债", "kiam"},
            {"好像", "kiamav"},{"睫毛", "kipkip"},
            {"国语", "kukugu"},{"脚", "kula"},
            {"ㄧ组(单位词)", "kumi"},{"镜子", "qailjungan"},
            {"照镜子", "qailjungan"},{"眼镜", "qailjungan"},
            {"石板", "qaljiv"},{"冲走", "qaljudj-"},
            {"稻谷", "qasalj"},{"虫", "qatjuvitjuvi"},
            {"竹子", "qau"},{"责备", "qelalj-"},
            {"柱子", "qeluz"}, {"粉末", "qemu"},
            {"强光刺眼", "qiljqilj-"}, {"杠杆", "qivaqiv"},
            {"...如此说", "qivu"}, {"…记载", "qivu"},
            {"讲话", "qivu"}, {"光头", "qunal"},
            {"烟斗", "qungcui"}, {"霉", "quveling"},
            {"粘贴", "kicaing"}, {"爱管闲事", "kicapiljan"},
            {"我身负的责任", "kucapilj"}, {"叮咛要盖被子", "kicauvu"},
            {"九月", "kugacu"},{"晚餐", "kaiven"},
            {"讨东西", "kemavulj"}, {"请求要求", "kemavulj"},
            {"赊帐", "kipukian"}, {"将肉切成条状", "kemitj"},
            {"切成段", "kitjen"},{"切", "kitjen"},
            {"离异", "kitjukuda"}, {"避雨", "kiljaljaung"},
            {"避烈阳", "kiljaljaung"},{"对话", "kiljavaran"},
            {"文告", "kiljavaran"},{"受虐者", "kinaparang"},
            {"勉强", "qemadilj"},{"抹香膏", "qemalev"},
            {"重口味", "qemapedang"},{"制作香肠", "qemapilj"},
            {"占有", "qemavas"},{"已酸臭", "qaveleveleng"},
            {"阻塞", "qemelec"},{"以杠杆支撑东西", "qemili"},
            {"争夺", "kiqizingan"},{"啃骨头", "qemucquc"},
            {"虹", "quljivangraw"},{"捆绑着", "qemuyulj"},
            {"畏惧", "kinarekutjan"},{"与...为伴", "kipusaladj"},
            {"要有羞耻心", "kasiaqu"}, {"表现差", "kisiaq"},
            {"不好意思", "kisiaq"}, {"天暗", "kasuleman"},
            {"天黑", "kasuleman"}, {"伞", "'ausua"},
            {"会长", "kaiciu"}, {"小蚊子", "kaljengkengan"},
            {"蝗虫", "kaljivungu"}, {"够了", "kameseng"},
            {"柚子", "kamurav"}, {"胸罩", "kavikavic"},
            {"煮饭", "kesa-"}, {"局", "kiuku"},
            {"拜访", "kivala"}, {"工厂", "kuba"},
            {"人面蜘蛛", "kumakuma"}, {"训练", "kunring"},
            {"癫痫", "qacang"}, {"痣", "qaceng"},
            {"男子名", "qaluvu"},{"太稀", "qasaw-"},
            {"酸臭味", "qaveleng"},{"前面", "qayav-"},
            {"领先", "qayav-"},{"极端", "qazalj-"},
            {"厉害", "qazalj-"},{"小气", "qeritic"},
            {"躲藏", "qilja-"},{"烤焦味道", "qim-"},
            {"覆盖物", "quleng-"},{"除去", "qulip"},
            {"消失", "qulip"},{"浓", "quljemu"},
            {"男子名", "quzang"},{"偷偷摸摸", "kicakav"},
            {"学习", "kicaquan"},{"测量", "qemacepang"},
            {"动过受术", "kiniceviqan"},{"独有", "kacidilj"},
            {"只有", "kacidilj"},{"去抓鱼", "kiciqav"},
            {"与某人同去", "kinidjadjalanan"}, {"招惹怒骂", "kikadudu"},
            {"唯一", "kaitan"}, {"来自…", "kasizuan"},
            {"穿裤子", "kemasui"}, {"很少", "kedrikeri"},
            {"很小", "kedrikeri"}, {"蹲葬", "kemuculj"},
            {"如何做", "kudain"}, {"没有办法", "kudain"},
            {"火烤", "kemuljav"}, {"削制瓜签", "kemuljus"},
            {"有…不会的", "kakulungen"}, {"下咒", "kemuyac"},
            {"感同深受", "kipavala"}, {"抹油", "qaleven"},
            {"客人", "qaljaqalja"}, {"极端", "kiqazalj"},
            {"显灵", "qemazalj"}, {"平民", "qaqetitan"},
            {"庶民", "qaqetitan"},{"抱", "qemevet"},
            {"藏匿", "qinilja"},{"油炒", "qemirqir"},
            {"用头巾包头", "kiquleng"},{"灰尘", "qunevuljan"},
            {"会发霉", "quvelingen"},{"正在捆绑…", "qemuyuquyulj"},
            {"投靠", "kirangez"},{"依靠", "kirangez"},
            {"改过自新之地", "kakiumaljan"},{"改过自新", "kiumaljanga"},
            {"葛玛兰族", "kavalanzuku"},{"运动场", "'unduziu"},
            {"对于自己兄长或姐姐同辈者的称谓", "kaka"},{"铃铛", "kalingking"},
            {"铃铛声", "kalingking"},{"眨眼", "kalipkip"},
            {"依然完整", "kamayan"},{"槟榔用篮", "kavatjes"},
            {"拉绳(特指用来拉摇篮及秋千之绳子)", "keli"},{"标记", "keljang"},
            {"相识", "keljang"}, {"检视", "keljang 2"},
            {"介绍", "keljang"}, {"获得…", "ki-"},
            {"偷偷摸摸", "kizaqav"}, {"锄头", "kuacui"},
            {"医生", "kuisang"}, {"鸡", "kuka"},
            {"穿上裙子", "kunan"}, {"翻转", "qadriv-"},
            {"倾斜", "qadriv-"}, {"双胞胎", "qaida"},
            {"芒草叶", "qaljup"}, {"呼气", "qas-"},
            {"鳞片", "qauljivan"}, {"黄莲木", "qaunip"},
            {"惊吓", "qavus-"}, {"作怪", "qavus-"},
            {"检验", "qayam-"}, {"尝试", "qayam-"},
            {"压制", "qepedj-"},{"压下", "qepedj-"},
            {"熄灭", "qevutj-"},{"压制", "qezet-"},
            {"做记号", "qezet-"},{"吵闹", "qiljengal"},
            {"黄", "qulivai"},{"田", "quma"},
            {"地", "quma"},{"说不出话", "qumu-"},
            {"腋毛", "quvis"},{"原住民族的方式(服装)", "kinacalisianan"},
            {"盖着", "kicauv"},{"真神", "kacemasan"},
            {"约会", "kicevungan"},{"森林", "kidjadjas"},
            {"预备", "kipadjele"},{"男子名", "kasikasiven"},
            {"背着袋子", "kemavic"},{"用汤匙舀", "kinizing"},
            {"样子", "kinakemudan"},{"干涸", "kinakuljian"},
            {"用水泥做的", "kinungkuli"}, {"两次", "kinmusalj"},
            {"屋顶", "qinaljivan"}, {"彼此勾肩", "qemapilj"},
            {"挖蚯蚓", "kiqatjurai"}, {"胸前", "qayav"},
            {"求助", "kiqeljing"}, {"在场", "kiqepu"},
            {"参与", "kiqepu"}, {"躲藏", "kiqilja"},
            {"正在说话", "qivuivu"}, {"被啃食", "qinucquc"},
            {"已经被啃食了", "qinucqucanga"}, {"真实的", "kaqulidan"},
            {"嘴巴含东西", "qemumu"}, {"卷的", "quringiringic"},
            {"没睡饱样", "quyuan"}, {"赶紧", "kirimu"},
            {"躺", "kisangel"}, {"令人怀念", "kinasingelitan"},
            {"照顾", "kivalisaked"},{"不听话", "kivaqil"},
            {"自己解脱", "kisuvengetj"},{"切除", "kivuciq"},
            {"所采的无患子", "kinizaqu"},{"话语", "kai"},
            {"针", "kala"},{"线", "kala"},
            {"高粱", "kalalumai"},{"灾难", "kapaula"},
            {"树木", "kasiv"},{"柴", "kasiv"},
            {"丛林", "kasiv"},{"和", "katua"},
            {"独有", "kavudilj"},{"少", "keri"},
            {"小", "keri"},{"爱心", "kiljivak"},
            {"母亲", "kina"},{"蹲", "kuculj-"},
            {"紫色", "kulimac"},{"肠子", "kuljai"},
            //l
            {"面粉", "lamug"}, {"腰带", "ledeled"},
            {"西方", "ledep-"}, {"猜谜", "liguligu"},
            {"棺木", "lukulj"}, {"一一的", "ljemita"},
            {"小指头", "ljaljakan"}, {"男子名", "ljaljeqelan"},
            {"假酸浆", "ljavilu"}, {"调整", "ljenguaq-"},
            {"修理", "ljenguaq-"}, {"舒适", "ljenguaq-"},
            {"起水泡", "ljetiq-"}, {"逗趣", "ljiqu"},
            {"壳", "rariq"}, {"阻栏", "rengez"},
            {"颈链", "reqel"}, {"一个单位", "ringuc"},
            {"经常欺骗", "ruburu"}, {"假神", "ljacemacemas"},
            {"六月", "lukugacu"},{"常携带", "rukacu"},
            {"吞食", "lemamedj"},{"常拿(隐喻偷窃)", "rualap"},
            {"煮", "lemikezalj"},{"很容易被逗笑", "ruljaqljaqan"},
            {"训勉", "ljemavaran"},{"正摇动", "ljemiuljiug"},
            {"探视", "ljemizaw"},{"倦怠", "luljaluljai"},
            {"捉弄", "ranaven"},{"促使和平", "remasudj"},
            {"尖尖的", "rudjudjum"},{"冲洗(特指地瓜和竽头)", "remugrug"},
            {"钝钝的", "runpenpenl"},{"占卜祭壶", "lalupeng"},
            {"杓子", "levec"},{"多", "liav"},
            {"溢", "liav"},{"历史", "likisi"},
            {"黄蜂", "lucluc"},{"使人生气、丧气", "lumalj-"},
            {"庇护", "ljakev-"}, {"小肩带", "ljavac"},
            {"鬼针草", "ljavangas"}, {"猴子", "ljavingan"},
            {"音质", "ljingav"}, {"声音", "ljingav"},
            {"探视", "ljizaw-"}, {"查看", "ljizaw-"},
            {"巫师问卜用之壶", "ljui"}, {"使不方便", "rapalj"},
            {"短", "rikitj"}, {"矮", "rikitj"},
            {"不好", "rikitj"}, {"急", "rimu-"},
            {"忙碌", "rimu-"}, {"日本", "rivu-"},
            {"烧水", "lemalja"}, {"嫩", "ledjeledje"},
            {"披风", "linipelip"},{"问候", "ai"},
            {"下聘", "lemisi"}, {"弄清楚", "ljemaljuai"},
            {"放松", "lemuka"}, {"入殓", "lemukulj"},
            {"辛劳", "luljayan"}, {"正在堆砌石墙", "remumul"},
            {"用拳头打", "remumul"}, {"滚", "remuqu"},
            {"呐", "dra"}, {"锻炼屋", "lalangan"},
            {"长", "laruq"}, {"高", "laruq"},
            {"丧礼肩巾", "lepec"}, {"女子名", "liljuk"},
            {"小气", "lisi"}, {"闹脾气", "luqic-"},
            {"捉弄人", "luqic-"}, {"荣耀礼", "ljakarav"},
            {"昭和草", "ljaluing"}, {"探访", "ljav-"},
            {"温馨", "ljav-"},{"解脱", "ljav-"},
            {"流感", "ljayar"},{"针", "ljigim"},
            {"低头", "ljuku"},{"能吃", "ramilj"},
            {"仰头", "reqang-"},{"马", "rigi"},
            {"弯", "rukung"},{"避开", "lemagav"},
            {"捕捉", "lemala"},{"下坡", "ljelauz"},
            {"撼动", "lemegeleg"},{"交界", "ljaljaqedian"},
            {"边界", "ljaljaqedian"},{"中文", "ljinautjian"},
            {"唱哀歌", "ljemayuz"},{"不受肯定", "lumaljen"},
            {"败坏", "rupaqatelengan"},{"正在台风", "remaljiraljiz"},
            {"爱吃醋的", "rukarengec"},{"说日语", "remipungan"},
            {"收拾", "remukuz"}, {"储藏", "remukuz"},
            {"抓进监狱", "remusung"}, {"高地的", "ljaizaya"},
            {"女子名", "dremedreman"}, {"连杯", "langalj"},
            {"连杯", "langalj"}, {"躺", "langalj"},
            {"仰卧", "langalj"}, {"赐予", "lavut"},
            {"自立", "lingdjelj-"}, {"设立", "lingdjelj-"},
            {"设立", "lingdjelj-"}, {"砖头", "lingga"},
            {"松", "luka-"}, {"口琴", "ljaljegean"},
            {"冷", "ljaljeqel"}, {"万寿菊", "ljangi"},
            {"腋下", "ljeqeljeqan"}, {"猫头鹰", "ljequ"},
            {"瞪", "ljiqedev-"},{"斜眼", "ljiqedev-"},
            {"晒", "rasi"},{"和解", "rasudj-"},
            {"皱纹", "rengec"},{"醋劲", "rengec"},
            {"滚动", "ruqu-"},{"蜡烛", "rusuku"},
            {"正在吞", "lemamelamedj"},{"光荣", "lemigu"},
            {"去敬酒", "ljagayu"},{"议题", "ljavaran"},
            {"逗笑", "ljiquin"},{"放在摇篮里", "ljemiug"},
            {"惹使生气", "lemuqic"},{"捉弄人", "lemuqic"},
            {"分给", "lemuvad"},{"分…给…", "luvadan"},
            {"催促", "remucruc"},{"尖的", "ruadjuadjum"},
            {"二元", "rusavatan"},{"专采无患子的人", "rukizaqu"},
            {"二", "drusa"}, {"苍蝇", "lalangaw"},
            {"烫伤", "laqut"}, {"老板", "laupan"},
            {"桑葚", "liljuk"}, {"脖子", "liqu"},
            {"阻碍", "lupi-"}, {"懒惰", "lupi-"},
            {"手腕", "ljakaljat"}, {"守护神", "ljaljumegan"},
            {"了解", "ljaluai-"}, {"嘴唇", "ljelet"},
            {"开玩笑", "ljikai-"}, {"故意", "ranav-"},
            {"自作自受", "ranav-"}, {"捉弄", "ranav-"},
            {"茅草(建筑用的)", "ravuc"}, {"畏惧", "regem-"},
            {"多话", "rukai"}, {"健谈", "rukai"},
            {"有爱心", "rukiljivakan"},{"闪电", "lemadjap"},
            {"捕捉的", "linalan"},{"连杯", "langalj"},
            {"满溢", "lemiav"},{"溢出来", "lemiav"},
            {"匍匐", "ljemaljap"},{"讲中文", "ljemautjian"},
            {"温馨", "ljavljavan"},{"捡到的", "ljinulju"},
            {"卷起", "lemutlut"},{"装在篮子里", "rinakuyan"},
            {"用茅草盖的", "rinavuc"},{"弯曲", "rukurukung"},
            {"领唱者", "rusenasenai"},{"下来", "ljeteku"},
            {"叉", "draqa"},{"女子名", "dresdres"},
            {"多排琉璃项链", "drinpa"},{"避开", "lagav-"},
            {"遗忘", "lagav-"},{"满溢", "laviq-"},
            {"苎麻绳", "lekelek"}, {"一捆(特指小米)", "lekelek"},
            {"女子名", "lingac"}, {"立法委员", "lipuiing"},
            {"痛苦", "lutud"}, {"痛", "lutud"},
            {"喊痛", "lutud"}, {"男子名", "ljagai"},
            {"瘀青", "ljanger"}, {"边界", "ljaqedi-"},
            {"邻居", "ljaqedi-"}, {"南瓜", "ljasiak"},
            {"使变成…", "ljeme-"}, {"看见", "ljengljeng-"},
            {"祭仪", "ljeveq-"}, {"瓶盖", "ljupetj"},
            {"锋利的", "radjai"}, {"火种", "ramac"},
            {"韧带", "rekec"}, {"垮", "revur-"},
            {"拆毁", "revur-"},{"石墙", "rumul"},
            {"诈骗集团", "rubulubulung"},{"远离一点", "ljiacadjau"},
            {"未经嚼食即吞咽", "lemqes"},{"切菜", "ljemaceng"},
            {"庇护", "ljemakev"},{"阴凉处", "ljaung"},
            {"鄙视", "ljememet"},{"轻视", "ljememet"},
            {"烧动物的毛", "ljemengis"},{"瞪", "lemiqeliqedev"},
            {"拾取", "ljemulju"},{"懒散", "lupilupi"},
            {"锹形虫", "ljaqecaqecap"},{"利用晚间", "remaqezemetj"},
            {"被拉", "rinakac"},{"晒谷场", "rarasian"},
            {"一拐一拐", "remialan"},{"弄弯曲的", "rinukung"},
            {"答应了", "ljemaui"},{"烧热水", "lalja-"},
            {"滚水", "lalja-"}, {"灰烬", "lavu"},
            {"摇动", "legeleg-"}, {"震动", "legeleg-"},
            {"撼动", "legeleg-"}, {"豹", "likuljav"},
            {"隔间", "livek"}, {"分配", "luvad-"},
            {"露珠", "ljadjek"}, {"扫帚", "ljaljumai"},
            {"对话", "ljavar-"}, {"议题", "ljavar-"},
            {"训勉", "ljavar-"}, {"造谣", "ljavar-"},
            {"轻视", "ljemet-"}, {"甩干", "ljiak-"},
            {"文株兰", "ljivakung"}, {"劈腿", "raqa"},
            {"分叉", "raqa"}, {"敬畏", "rekutj-"},
            {"胆小", "rekutj-"},{"陶壶(有雕纹的)", "reretan"},
            {"尖", "rudjum-"},{"常打鼾", "ruvarequn"},
            {"热水", "linalja"},{"细的", "linedje"},
            {"常生气的", "rulimuceng"},{"雨具", "ljaung"},
            {"河岸", "ljemavingan"},{"逗乐", "ljemiqu"},
            {"放低身体", "ljemaljukuan"},{"使成熟", "lemum"},
            {"扳着脸", "limuceng"},{"不喜欢", "limuceng"},
            {"生气", "limuceng"},{"时常缺课", "rupulavai"},
            {"使...晒", "remasi"},{"胆小鬼", "rurekutjan"},
            {"短的", "rikirikitj"},{"被…滚动", "rinuqu"},
            {"女性朋友", "drava"},{"鼾声", "drequng"},
            {"闪电", "ladjap"}, {"短暂", "lamu-"},
            {"过份", "lamu-"}, {"允许", "lamu-"},
            {"凹陷", "likeljung"}, {"低洼", "likeljung"},
            {"木汤盆", "lingadja"}, {"智慧", "lingav-"},
            {"急促", "lingav-"}, {"时间", "lingav-"},
            {"急促", "lingav-"}, {"六", "luku"},
            {"匍匐前进", "ljaljap-"}, {"游泳", "ljangui-"},
            {"游泳池", "ljangui-"}, {"玉米", "ljapanai"},
            {"栉芒(芒草)", "ljavia"}, {"桑树", "ljisu"},
            {"勇士", "rakac"}, {"篮子", "rakui"},
            {"关节种称", "raregeregan"},{"陷阱", "ringai"},
            {"工具钝了", "runpel-"},{"沾到", "rupaq-"},
            {"荣幸", "levan"},{"低洼的", "likeljukeljung"},
            {"敬酒", "ljemagai"},{"正在敬酒", "ljemagaljagai"},
            {"了解", "ljemaluai"},{"每年", "ljemitacavilj"},
            {"置于棺木", "lukuljen"},{"轻视", "lemuqem"},
            {"请分", "luvadu"},{"经常迟疑", "rupaivatjan"},
            {"忍耐", "rukiqadilj"},{"伍堆", "limaaqepuan"},
            {"被拉", "rakacen"},{"拉", "remakac"},
            {"被…揍", "rinumul"},{"玛瑙珠", "drimukui"},
            {"吞咽", "lamedj-"},{"食道", "lamedj-"},
            {"迫害", "lapai-"}, {"严重", "lapai-"},
            {"痛苦", "lapai-"}, {"飞鼠", "lava"},
            {"头晕", "lingac-"}, {"披肩", "liplip"},
            {"蒸汽", "liulj"}, {"秋蝉", "ljaljai"},
            {"蜈蚣", "ljaljiga"}, {"烧化", "ljama-"},
            {"烧", "ljengis"}, {"凌晨", "ljia"},
            {"混浊", "ljimek"}, {"喉结", "raqul"},
            {"同性朋友(女朋友)", "rava"}, {"各位", "reka"},
            {"敬礼", "requng"}, {"揍人", "rumul-"},
            {"用拳头打", "rumul-"}, {"胆寒", "regiljic"},
            {"走廊", "liljililjing"},{"陪伴", "ljemaveljav"},
            {"给予温暖", "ljemaveljav"},{"斜眼", "lemiqeliqedev"},
            {"查看(探看", "ljemizaw"},{"(古壶)月亮的眼泪", "luseqnaqiljas"},
            {"正在隐隐作痛", "lemutulutud"},{"再靠右边一点", "ljianavalj"},
            {"引导", "remakac"},{"传统服饰", "ravaravain"},
            {"恐惧害怕", "rekutjan"},{"清理", "rugrug"},
            {"悲悯之心", "rusaleljeseljan"},{"乐于服役", "rukisekaulj"},
            {"蝌蚪", "laliqu"},{"下方", "lauz"},
            {"烘干", "lemavlav"},{"遮荫", "liljing"},
            {"赤裸", "liqaqut-"},{"有能力", "luqem"},
            {"有气魄", "luqem"},{"秋千", "ljakai"},
            {"面对面", "ljaljungu"}, {"遮蔽", "ljaung-"},
            {"阴凉处", "ljaung-"}, {"雨具", "ljaung-"},
            {"阴凉", "ljelem-"}, {"甩一甩", "ljikljik"},
            {"长形", "ljungaruq"}, {"草药", "racev"},
            {"漂流木", "ramalj"}, {"很", "ravac"},
            {"男子名", "rias"}, {"清理", "rugrug-"},
            {"洞穴", "lala"}, {"捕捉", "lala"},
            {"很长", "laruaruq"}, {"请你摇动", "legelegu"},
            {"吞食", "lemimqu"}, {"感觉到冷", "ljemaljeqel"},
            {"有疤", "ljaqiljaqican"}, {"探访", "ljemavljav"},
            {"正在看", "ljemengljengljeng"},{"混浊的", "ljimeljimek"},
            {"堵住", "ljupetjen"},{"被卷起来", "linutlut"},
            {"存放得很好", "ljinenguaq"},{"爱哭鬼", "ruqauqaung"},
            {"为…准备", "rinava"},{"干炒", "remingiring"},
            {"好动", "rusepeljan"},{"放低一点", "ljiateku"},
            {"樟树", "drakes"},{"猪", "dridri"},
            {"长子", "laing-"},{"顺服", "laing-"},
            {"追随", "laing-"},{"领导者", "laing-"},
            {"监视", "laing-"},{"受照顾", "laing-"},
            {"球蕨", "lavucuvucu"},{"肋骨", "ledje-"},
            {"细", "ledje-"},{"嫩", "ledje-"},
            {"手", "lima"}, {"五", "lima"},
            {"同桌", "lingulj-"}, {"周围", "lingulj-"},
            {"包围", "lingulj-"}, {"团聚", "lingulj-"},
            {"兔子", "lutjuk"}, {"野菜", "ljaceng"},
            {"青菜", "ljaceng"}, {"美丽的青少女", "ljaceng"},
            {"清澈", "ljamecav"}, {"逗趣", "ljaqljaq-"},
            {"风闻", "ljeminga"}, {"抱怨或微词", "ljeminga"},
            {"听觉", "ljiabar"}, {"专注倾听", "ljiabar"},
            {"漏斗", "ljutu"}, {"鸭子", "raimai"},
            {"台风", "raljiz"}, {"对温度的感受", "regem-"},
            {"鼾声", "requng-"},{"高梁", "rumagai"},
            {"兽栏", "ruvu"},{"听到", "lemangda"},
            {"阴凉处树荫", "ljauljaung"},{"修理", "ljemenguaq"},
            {"整理", "ljemenguaq"},{"瞪", "lemiqedev"},
            {"低着头", "ljemuku"},{"好命", "rupuqimangan"},
            {"晒了", "rinasi"},{"忘记", "remauraw"},
            {"阻挡", "remengez"},{"拆除", "remevur"},
            {"关入兽栏", "remuvu"},{"五元", "limavatan"},
            {"男子名", "drangadrang"},{"确认", "dri"},
            {"听", "langda-"},{"听话", "langda-"},
            {"喇叭", "lappa-"},{"荣幸", "leva-"},
            {"高兴", "leva-"}, {"高兴", "leva-"},
            {"喜爱", "leva-"}, {"肃静", "liceng"},
            {"吞", "limqu-"}, {"伙伴", "lingulj"},
            {"陪伴", "lingulj"}, {"圆形", "lipuru"},
            {"水果成熟", "lum"}, {"但是", "ljakua"},
            {"生姜", "ljamljam"}, {"疤痕", "ljaqic"},
            {"靠南方之处(也称靠近平坦之地)", "ljavljav"}, {"电话", "ljingas"},
            {"早起", "ljuvaq-"}, {"比赛", "ljuvaq-"},
            {"更严重", "racuk-"}, {"准备小米田", "ramac"},
            {"收成时遗漏田园之物", "raumalj"}, {"笔茼树", "rikis"},
            {"虾笼", "rumuk"},{"监狱", "rusung"},
            {"长舌妇", "rukaikai"},{"用手制成的", "linima"},
            {"做成圆形的", "linipuru"},{"庇护", "ljakeven"},
            {"游泳池", "ljaljanguyan"},{"弄坏", "ljemekuya"},
            {"看清楚", "ljemengljeng"},{"甩干", "ljemiak"},
            {"阻碍", "lemupi"},{"小气", "luqiluqic"},
            {"靠过来", "ljaimaza"},{"靠这一边", "ljaimaza"},
            {"很会惹事", "rupitiqan"},{"贪心之人", "ruqaravanan"},
            {"伴芋头粉", "remagrag"},{"正在忽冷忽热", "regeregeman"},
            {"仰头", "remeqang"},{"长出枝子", "ricingan"},
            {"繁复", "rimuan"},{"鲁凯族", "rekaizuku"},
            {"落选", "lakesing"}, {"伸出火舌", "lemidam"},
            {"吞咽", "leqes-"}, {"绿", "liljuas"},
            {"板着脸", "litengic"}, {"轻视", "luqem-"},
            {"眼泪", "luseq"}, {"敬酒", "ljagai-"},
            {"痕迹", "ljatel"}, {"汉人", "ljautjia"},
            {"喜泣之歌", "ljayuz"}, {"乍现", "ljimamur-"},
            {"前小腿", "ljungudan"}, {"耆老", "ramaljeng"},
            {"树枝", "ricing"}, {"礼拜", "rihai"},
            {"困惑", "rucruc"}, {"记录", "ruku-"},
            {"常偷", "rucakav"}, {"叉形", "draqadraqa"},
            {"亲密朋友", "dravadrava"},{"手伸入洞穴里", "lemala"},
            {"摇动", "lemegeleg"},{"正在生气", "limucemuceng"},
            {"包围", "lemingulj"},{"冷了", "ljaljeqeljeqel"},
            {"游泳", "ljemangui"},{"邻居", "ljaqediqedi"},
            {"使人丧气", "lemumalj"},{"性欲强烈", "ruqazimanan"},
            {"照顾", "remapalj"},{"爬上", "remaqiz"},
            {"请你…滚…", "ruquu"},{"禁闭室", "rarusungan"},
            {"获…准", "ljinaui"},{"不诚实", "ruveca"},
            {"靠左边一点", "ljiaviri"},{"水管", "laljing"},
            {"拿", "lap-"},{"代收", "lap-"},
            {"代替", "lap-"},{"米糠", "lapi"},
            {"后面", "likuz-"}, {"边境", "livai-"},
            {"不给面子", "livai-"}, {"走错路", "livai-"},
            {"令人劳累", "luljai-"}, {"疲惫", "luljai-"},
            {"清楚", "ljaluai"}, {"散发", "ljaljiak-"},
            {"九层塔", "ljaljikang"}, {"球蕨羊齿", "ljavucuvucu"},
            {"铁丝", "ljingas"}, {"摇篮", "ljiug"},
            {"向上爬", "raqiz-"}, {"忘记", "rauraw-"},
            {"打扮", "rava-"}, {"准备", "rava-"},
            {"麻绳", "rava-"}, {"多产", "rualjak"},
            {"靠近", "ljiadet"}, {"惧怕", "remegiljic"},
            {"更下去一点", "ljialauz"},{"绿色的", "liljualjuas"},
            {"青竹丝", "liljualjuas"},{"用成圆型的", "lipuruin"},
            {"边境", "livalivai"},{"岸边", "ljaviljaving"},
            {"起水泡", "ljemetiq"},{"使混浊", "ljemimek"},
            {"痛苦", "lemutud"},{"埋葬", "lemuvang"},
            {"二十", "drusapuluq"},{"包礼", "remaljuv"},
            {"忽冷忽热", "regeman"},{"吓人", "remekutj"},
            {"将手放置腰后", "remikul"},{"繁忙", "rimurimuan"},
            {"去捕捉", "remingay"},{"男子名", "draqili"},
            {"潜", "ledep-"},{"木碗", "lidapai"},
            {"荣耀", "ligu"},{"论文", "lunbun"},
            {"凹陷", "luvang"}, {"窟窿", "luvang"},
            {"家族名", "ljapaqadriv"}, {"海洋", "ljavek"},
            {"陪伴", "ljaveljav-"}, {"给予温暖", "ljaveljav-"},
            {"抽取", "ljisuk"}, {"拉", "rakac-"},
            {"复原", "rakac-"}, {"时间", "raketj-"},
            {"主角", "raketj-"}, {"干炒", "ringiring-"},
            {"男子名", "ringuc"}, {"搬弄是非", "ruangalj"},
            {"土质不稳定", "rukacunuq"}, {"追", "lemaing"},
            {"引水", "lemaljing"}, {"设立", "lemingdjelj"},
            {"圆形的", "ljemama"}, {"烧", "ljemama"},
            {"放火烧", "anasui"},{"有烧", "ljinama"},
            {"逗趣", "ljaqljaqen"},{"两堆", "drusaqepuan"},
            {"扮鬼脸", "remanav"},{"将拿东西之手放置腰后", "rinikul"},
            {"拳击", "rinumul"}, {"很害羞", "rusiaqan"}, 
            {"愣住", "retjegel"},{"青铜刀总称", "dragaman"},
            {"专指收割后遗漏的稻穗", "lagav"},{"烤窑", "leku"},
            {"愚蠢", "levlev"},{"炉灶", "likezalj"},
            {"软", "lumeljak"},{"卷起", "lutlut-"},
            {"属于那一家", "lja-"},{"刺茄", "ljasaras"},
            {"掌管", "ljavak-"},{"管辖", "ljavak-"},
            {"边缘", "ljaving"},{"黄牛", "ljuang"},
            {"骨髓", "ljuseq"}, {"芋头粉", "ragrag"},
            {"依靠", "rangez-"}, {"托付", "rangez-"},
            {"一跛一跛", "rial-"}, {"将手放置腰后", "rikul-"},
            {"男子名", "ripun"}, {"孕育", "rukuz-"},
            {"储藏", "rukuz-"}, {"存放", "rukuz-"},
            {"包", "rukuz-"}, {"不知道", "likuculjen"},
            {"芋头干", "aradj"}, {"使蹲姿", "ariqa"},
            {"烧水之处或器皿", "lalaljan"}, {"肋骨", "ledjeledje"},
            {"被摇动", "linegeleg"}, {"急促(尿急)", "lingav"},
            {"时间", "lingav"}, {"砖造的", "liningga"},
            {"用披肩包裹", "lemipelip"},{"正在烧猪毛", "ljemengiljengis"},
            {"修理", "ljemenguaq"},{"容易生气", "lumalumalj"},
            {"低头", "remequng"},{"垂头丧气", "remequng"},
            {"被堆砌", "rinumul"},{"被关入监狱", "rinusung"},
            {"答应吧", "ljauiu"},{"常出去", "ruvaik"},
            {"万", "kurav"}, {"阴茎", "qalici"},
            {"捕鼠夹", "qaljangetj"}, {"铁夹子", "qaljangetj"},
            {"穿山甲", "qam"}, {"贪心", "qaravan"},
            {"贪图", "qaravan"}, {"盐巴", "qatia"},
            {"壁虎", "qatjatjipi"}, {"抢夺", "qav-"},
            {"防灾巷", "qelicung"}, {"闭塞", "qeljepetj-"},
            {"拔河", "qesir"}, {"椅子", "qiladj-"},
            {"臀部", "qiladj-"}, {"丧礼", "qipel-"},
            {"男子名", "qipu"}, {"便秘", "qucel-"},
            {"树蛙", "quraqur"}, {"云", "qurepus"},
            {"深色", "quzemai"},{"用竹子做可以装水的玩具", "qaberes"},
            {"东方的", "kacedasan"},{"模仿", "kicual"},
            {"学习", "kicual"},{"典范", "kicual"},
            {"侧身", "kigidi"},{"方言", "kinakaikaian"},
            {"使钩上", "kalavisu"},{"知识", "kinljangan"},
            {"寻物", "kemim"},{"警察局", "keisackiuku"},
            {"不满", "kisankuya"},{"难过", "kisankuya"},
            {"不雅", "kuyakuya"},{"采菜", "kiljaceng"},
            {"买菜", "kiljaceng"},{"不同", "kisumalji"},
            {"设想", "kinemnem"},{"鼻屎", "qungec"},
            {"开会", "kaigi"},{"挖出的洞", "kali"},
            {"女性神人名", "kaljalju"}, {"吃", "kan-"},
            {"食物", "kan-"}, {"餐具", "kan-"},
            {"上衣", "kava"}, {"苦瓜", "kawkuy"},
            {"早餐", "kenama"}, {"冰", "kiaping"}
            {"教堂", "kiukai"}, {"规矩", "kuda-"},
            {"工作", "kuda-"}, {"结果", "kuda-"},
            {"高跷", "kulakula"}, {"公路", "kunglu"},
            {"翻滚", "qaluresing"}, {"滑", "qalamqam"},
            {"扁形工艺品", "qaripi-"}, {"带状疱疹", "qatjuvi"},
            {"喊叫", "qauqav"}, {"趴", "qazav-"},
            {"后院", "qeljuan-"},{"辗压", "qetjeqetj-"},
            {"青蛙", "qiav"},{"红", "qudjilj"},
            {"金黄色", "quljizar"},{"孩子们", "qunu"},
            {"束", "quyulj"},{"绑", "quyulj"},
            {"包工程", "kibau"},{"年份", "kinacaviljan"},
            {"年运", "kinacaviljan"},{"看诊", "kipucemel"},
            {"刻意仿效", "kicuacual"},{"被责备", "kinaduduan"},
            {"祷告室", "kaka'inulian"},{"携带着", "kacuin"},
            {"弄乱", "karadikad"},{"摆动", "kemeli"},
            {"小孩子", "kakerian"},{"问某人", "kipakim"},
            {"做什么事", "kudakudain"},{"减肥", "kipapekuljai"},
            {"踩煞车", "kemuseta"}, {"要听话", "kilangdau"},
            {"同桌", "kilingulj"}, {"取部分", "kiluvad"},
            {"测量", "kipakeciu"}, {"允诺", "kipenetj"},
            {"滑溜的样子", "qalamqaman"}, {"淡淡的", "qaljesaljesav"},
            {"打猎", "qemaljup"}, {"太低", "qemaput"},
            {"鸟类", "qayaqayam"}, {"储存", "qemedjen"},
            {"取..汁", "kiqetim"}, {"挤奶", "kiqetim"},
            {"隐秘处", "qiljaqilja"}, {"阴暗", "qiljaqilja"},
            {"荒芜的", "qucaqucalj"}, {"淋雨", "kipaqudjalj"},
            {"起云雾", "qemurepus"}, {"自卑", "kisangatj"},
            {"挑食", "kisavid"},{"被选为…", "kinasinkiu"},
            {"亲属", "kasusu"},{"三连蛇背之杯", "kaljutelu"},
            {"文身", "kivecik"},{"夏季", "kaljazalangzangan"},
            {"鱼罐头", "kanzumi"},{"与某人同去", "kinidjadjalanan"},
            {"招惹怒骂", "kikadudu"},{"唯一", "kaitan"},
            {"带着", "kacu"},{"咬他", "kacu"},
            {"天空", "kalevelevan"},{"蜘蛛网", "kaljualaq"},
            {"瓮", "kapua"},{"陶瓷", "kapua"},
            {"地板", "kasintan"},{"挂钩", "kelai"},
            {"作为", "kinudan"},{"不是滋味", "kisanparangan"},
            {"袜子", "kucusta"},{"老鼠", "kulavav"},
            {"不好", "kuya-"}, {"不满", "kuya-"},
            {"油脂", "qalev"}, {"栅栏", "qapaz"},
            {"蛇", "qatjuvi"}, {"蟑螂", "qauzung"},
            {"倾诉", "qeci-"}, {"控诉", "qeci-"},
            {"不雅", "qetit-"}, {"贫困", "qetit-"},
            {"抱", "qevet-"}, {"窗户", "qezung"},
            {"泥土", "qipu"}, {"彩虹", "quljivangeraw"},
            {"敬奉", "qunvulj"},{"有关系的", "kapacacapilj"},
            {"家庭", "kinacemkeljan"},{"典范", "kakicualan"},
            {"请握紧", "kigemgemu"},{"搅拌", "kemadiad"},
            {"带琉璃手链", "kemaljat"},{"吃掉了", "kanen"},
            {"平坦的", "kazatjazatjan"},{"厨房", "kakesan"},
            {"问", "kivadaq"},{"监视", "kilalaingan"},
            {"破坏", "kemapalak"},{"掉头", "kipenid"},
            {"抬着", "qaluin"},{"…做的小米糕", "qinavay"},
            {"关卡", "qaqeljevan"},{"取火", "kisapui"},
            {"顺从相信", "kisusu"}, {"手术台", "kakivuciqan"},
            {"认识", "kakeljangan"}, {"很帅", "kusta"},
            {"忍耐", "qadilj-"}, {"还是", "qeljemud"},
            {"挨饿", "kiculja"}, {"多次经常", "karim"},
            {"撕破", "kemuya"}, {"朋友", "kinelialiav"},
            {"悠闲的", "kiquca"}, {"下雨", "qemudjalj"},
            {"买", "kiveli"}, {"根", "kapaz"},
            {"我的…", "ken-"}, {"是我…", "ken-"},
            {"火车", "kisia"}, {"脚踝", "kuzkuzan"},
            {"悲痛", "qaung"}, {"请求", "qaung"},
            {"另一半", "qecev"},{"原住民", "kacalisian"},
            {"介入", "kicapilj"},{"停留", "kidjekec"},
            {"咬", "kemac"},{"玩具枪", "kuakuang"},
            {"亲自", "kimadju"},{"独自", "kimadju"},
            {"右手", "kanavalj"},{"何时(来)", "kangida"},
            {"福气", "kamanguaq"},{"道歉", "kipaqaljai"},
            {"完成", "qemacuvung"},{"苦苦的", "qadiadid"},
            {"分送", "qemarut"},{"作怪", "qemavus"},
            {"睡觉", "qemreng"},{"躺着", "qemreng"},
            {"缺水", "kinasuqudjaljan"},{"旱灾", "kinasuqudjaljan"},
            {"追究", "kisasusu"},{"运动", "'undu"},
            {"包包", "kabang"}, {"吃晚餐", "kaiv"},
            {"指甲", "kaljuskusan"}, {"小竹篮", "kavatjes"},
            {"为什么", "ku"}, {"一千", "kuzulj"},
            {"色泽", "quljav"}, {"颜色", "quljav"},
            {"留在", "kiadjuq"}, {"采收小米", "kivaqu"},
            {"追随", "kipalaing"}, {"取暖", "kingidju"},
            {"结交朋友", "kipuqali"}, {"卧房", "qaqerengan"},
            {"聚会", "kinateveteveljan"}, {"电影", "'iga"},
            {"响", "kaljeling"}, {"雨衣", "kappa"},
            {"碗", "kisi"}, {"夹子", "qaljapitj"},
            {"别人", "qaliqali"},{"陌生人", "qaliqali"},
            {"检视", "qemayam"},{"坐下", "qemiladj"},
            {"红色的", "qudjidjilj"},{"婴儿", "qunuqunu"},
            {"习惯于", "kitavak"},{"学习的地方", "kakituluan"},
            {"换钱", "kivalit"},{"土地", "kadjunangan"},
            {"石头", "qaciljai"},{"小米糕", "qavai"},
            {"筷子", "qecap"},{"夹", "qecap"},
            {"饲料", "quzu"},{"庭院", "kacasavan"},
            {"吃", "keman"},{"早起", "kiljuvaq"},
            {"遭遇", "kipaula"},{"石板屋", "qinaciljai"},
            {"哭", "qemaung"},{"下雨的", "qemudjaqudjalj"},
            {"雨天的", "qemudjaqudjalj"}, {"动物", "qemuzimuzip"},
            {"昨天", "katiaw"}, {"从…", "kemasi"},
            {"枪", "kuang"}, {"猪", "qacang"},
            {"粪便", "qacang"}, {"身体", "kinacavacavan"},
            {"吃午餐", "kincengelj"}, {"食物", "kakanen"},
            {"主动的", "kisumadju"}, {"晚上", "qezemezemetj"},
            {"改过", "kiumalj"}, {"玩", "kivangavang"},
            {"大武山", "kavulungan"}, {"雨", "qudjalj"},
            {"下雨", "qudjalj"}, {"堆", "qepuan"},
            {"椅子", "qiladjan"}, {"要种植之地", "qaqumain"},
            {"农作物", "qinuman"},{"工作", "kipusengsengan"},
            {"学习", "kitulu"},{"真诚", "kalja"},
            {"芒果", "kamaya"},{"我的…", "ku"},
            {"大", "qaca"},{"多", "qaca"},
            {"高", "qaca"},{"蛋", "qecilu"},
            {"月亮", "qiljas"},{"头", "qulu"},
            {"携带背着", "kinacu"},{"如何", "kemuda"},
            {"作品", "kinasengseng"},{"朋友", "qali"},
            {"琉璃珠", "qata"},{"哭泣", "aqaung"},
            {"试", "qemayam"},{"床", "qerengan"},
            {"黑色的", "qucengecengel"},{"种植", "qemuma"},
            {"价格", "kakavelian"}, {"平坦", "kazatjan"},
           



         
            

        };

}
